### ISSUE TITLE
Any plans of releasing Pre- Trained Weights?

### ISSUE THREAD

**Issue by deshwalmahesh** [kartikgill/Easter2#1]
Hi, 
Great work first of all. Had been looking for something like this last year. I've updated the [leader board over Paperwswithcode](https://paperswithcode.com/sota/handwritten-text-recognition-on-iam). Please change in case you feel I made a mistake.

Also, any plans of releasing the pre-trained weights?

**Comment by kartikgill** [comment]
Hey Mahesh!

Glad that you liked the work.
Yes! Pre-trained weights have been provided in the Github release.
