### ISSUE TITLE
Weights for model without TACo augmentations

### ISSUE THREAD

**Issue by cs-mshah** [kartikgill/Easter2#11]
Can you also share the weights of the model without any augmentation. It would be nice if you share weights of other models with different augmentations as given in table 4 of your paper.

**Comment by kartikgill** [comment]
Hey @cs-mshah,
I am no longer working this project...and hardly get any time to check it out. So, would not be able to help hear...sorry for that.
But i hope that with given code, you can experiment lot of things yourself. 
If you do - kindly post your interesting findings. Thanks.
