### ISSUE TITLE
the demo and pretrained checkpoint

### ISSUE THREAD

**Issue by dreamlychina** [kartikgill/Easter2#14]
could please show the demo of infering one image and give us the link of the pretrained checkpoint??

**Comment by Michael95-m** [comment]
@dreamlychina , You can see how to predict the single image in this [repo](https://github.com/Michael95-m/Easter2). The pretrained model is in readme too.

**Comment by kartikgill** [comment]
Thanks @Michael95-m , 
For taking this forward and adding more functionalities. 
@dreamlychina I hope you issue is resolved now......so closing it. Please feel free to reopen in case you still face issues. Thanks.
