### ISSUE TITLE
saved_checkpoint.hdf5 throwing keyerror

### ISSUE THREAD

**Issue by uthambathoju** [kartikgill/Easter2#2]
Hi Kartik,

When i' m trying to load the saved_checkpoint.hdf5 file, i'm getting below error looks like it is corrupted.

line of code : test_on_iam(show=True, partition="validation", checkpoint=checkpoint_path, uncased=True)

Error : from load_easter_model(checkpoint_path) function
KeyError: 'Unable to open object (bad heap free list)'

**Comment by kartikgill** [comment]
Hey Utham,

Could you share full error trace? 
And if possible, steps to reproduce!

**Comment by uthambathoju** [comment]
Hi Kartik,

Great work on HTR  and I really enjoyed reading both the EASTER and EASTER2.0 papers.

I'm running it on google colab and it is working fine now. It was my mistake that i have imported same python files with different names into the environment and because of this probably i was getting above error yesterday. Its all good now.

By any chance , is there a code repo for the first version of EASTER model.
