### ISSUE TITLE
Unable to run inference.

### ISSUE THREAD

**Issue by ankit066** [kartikgill/Easter2#3]
I am trying to run prediction on IAM dataset. Getting an error while loading saved_checkpoints from release section.The error is unable to load checkpoints.

**Comment by kartikgill** [comment]
Hey Ankit,

Can you drop full error trace here!

**Comment by ankit066** [comment]
I am using tensorflow ==2.5.0 , python== 3.8.10 and using docker for the same.
![Screenshot from 2022-06-20 19-01-35](https://user-images.githubusercontent.com/85393016/174614195-c20070f9-381d-49af-85ff-8cbbfac22404.png)


I guess this issue is related to model loading.

**Comment by kartikgill** [comment]
Can you quickly go to 'predict.py', and remove <try, catch> block from function "load_easter_model". this will give you exact error. If you can paste that error here, i may be able to help you.

**Comment by ankit066** [comment]
After removing <try,except> from the load_easter_model in predict.py . I am getting the same error.

loading metdata...
loading checkpoint...
calculating results...
Using Test Partition
  0%|          | 0/2915 [00:00<?, ?it/s]
Number of Samples :  2915


---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-c8a81b56cea8> in <module>
----> 1 test_on_iam(show=False, partition="test", checkpoint=checkpoint_path, uncased=True)

/workspace/easter/src/predict.py in test_on_iam(show, partition, uncased, checkpoint)
     91             img = imgs[i]
     92             truth = truths[i].strip(" ").replace("  "," ")
---> 93             output = model.predict(img)
     94             prediction = decoder(output, charlist)
     95             output = (prediction[0].strip(" ").replace("  ", " "))

AttributeError: 'NoneType' object has no attribute 'predict'

**Comment by ankit066** [comment]
When i have removed the <try,except> block and try to run without it  I am getting the following error .

loading metdata...
loading checkpoint...
calculating results...
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-c8a81b56cea8> in <module>
----> 1 test_on_iam(show=False, partition="test", checkpoint=checkpoint_path, uncased=True)

/workspace/easter/src/predict.py in test_on_iam(show, partition, uncased, checkpoint)
     89     print ("calculating results...")
     90 
---> 91     model = load_easter_model(checkpoint)
     92     char_error = 0
     93     total_chars = 0

/workspace/easter/src/predict.py in load_easter_model(checkpoint_path)
     33            checkpoint_path,
     34            custom_objects={'<lambda>': lambda x, y: y,
---> 35            'tf':tf})
     36 
     37     EASTER = tensorflow.keras.models.Model(

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/save.py in load_model(filepath, custom_objects, compile)
    141   if (h5py is not None and (
    142       isinstance(filepath, h5py.File) or h5py.is_hdf5(filepath))):
--> 143     return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
    144 
    145   if isinstance(filepath, six.string_types):

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/hdf5_format.py in load_model_from_hdf5(filepath, custom_objects, compile)
    160     model_config = json.loads(model_config.decode('utf-8'))
    161     model = model_config_lib.model_from_config(model_config,
--> 162                                                custom_objects=custom_objects)
    163 
    164     # set weights

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/model_config.py in model_from_config(config, custom_objects)
     53                     '`Sequential.from_config(config)`?')
     54   from tensorflow.python.keras.layers import deserialize  # pylint: disable=g-import-not-at-top
---> 55   return deserialize(config, custom_objects=custom_objects)
     56 
     57 

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/layers/serialization.py in deserialize(config, custom_objects)
    103       module_objects=globs,
    104       custom_objects=custom_objects,
--> 105       printable_module_name='layer')

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/utils/generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    178     config = identifier
    179     (cls, cls_config) = class_and_config_for_serialized_keras_object(
--> 180         config, module_objects, custom_objects, printable_module_name)
    181 
    182     if hasattr(cls, 'from_config'):

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/utils/generic_utils.py in class_and_config_for_serialized_keras_object(config, module_objects, custom_objects, printable_module_name)
    163     cls = module_objects.get(class_name)
    164     if cls is None:
--> 165       raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
    166   return (cls, config['config'])
    167 

ValueError: Unknown layer: Functional

**Comment by kartikgill** [comment]
Hey Ankit,

Thanks for the error trace.

Sorry i forgot to mention earlier, can you try with TF version, >= 2.6 once. If you still get error, please paste that new trace here.

**Comment by ankit066** [comment]
Hi Kartik,
I am still getting the same error i have tried with latest tensorflow version i.e 2.9.0.

**Comment by kartikgill** [comment]
Can you share the steps to reproduce, if possible? or try once on Google Colab, if that solves your problem!

**Comment by ankit066** [comment]
Hi kartik ,
I have tried to run inference on google colab and still facing the same error.
Steps :
Installing the necessary requirements.
Cloning the repository and weights from the release section putting them into weights folder.
Changing the path in config.py file for weights and data.
 Running the testing notebook from the notebooks section.

**Comment by satya400** [comment]
Hi Ankit, 

Just in case you are trying this code in google colab like me, in the testing note book, 

just before the below line:
test_on_iam(show=False, partition="validation", checkpoint=checkpoint_path, uncased=True)

add a new cell and run the below code:
import tensorflow as tf
from easter_model import Easter2
model = Easter2()

The above solved the error for me.  Just sharing.

Thanks
Satya

**Comment by kartikgill** [comment]
Awesome! Thanks @satya400.  @ankit066 I hope you are able to run the inference now.
-- closing this issue...please feel free to re-open if needed.
