### ISSUE TITLE
IAM statistics in the paper

### ISSUE THREAD

**Issue by itsbvk** [kartikgill/Easter2#4]
Hello Authors! Great work. 

I just found the statistics provided in the arxiv pre-print a little bit confusing. While presenting the IAM dataset stats, it looked like there are 64 lac training images. The different commas used for decimal separation and for separation of two different numbers became apparent to me only when I want to check the statistics in the IAM website. Please re-phrase the sentence :

___
![Screenshot 2022-08-27 at 2 51 50 PM](https://user-images.githubusercontent.com/57064909/187024695-fa59a4a1-6e4a-4cc5-91e9-8b56d4912242.png)

to 

IAM A has about 6,482 lines for training , 976 for validation and 2,915 for testing. IAM-B has about 6,161 for training, 940 for validation and 1,861 for testing.

___

On first read, I computed 10% of IAM as 6 lac and was wondering how could that be called few-shot?

**Comment by raghavbali** [comment]
@khadiravana-belagavi thanks for going through the paper and your inputs. We can indeed improve upon the confusing commas 😄 . Cheers

**Comment by itsbvk** [comment]
@raghavbali Not sure (xD) if there are ways to improve on the commas. But will be very helpful and grateful if it can be rephrased as mentioned. i.e. the sentence can be modified to :


IAM A has about 6,482 lines for training, 976 for validation, and 2,915 for testing. IAM-B has about 6,161 for training, 940 for validation, and 1,861 for testing.

The main purpose is that we should appreciate the fact that with such less number of samples, a good accuracy has been achieved. With the current sentence, people will walk away thinking there are 64 lac samples (I am not the only one to be confused - many others also have).
