### ISSUE TITLE
Can't load checkpoint: bad marshal data

### ISSUE THREAD

**Issue by Mekacher-Anis** [kartikgill/Easter2#5]
**Context:**
I have followed the instructions in the Readme file (download the latest checkpoint and placed it in the correct folder)
I tried to test the model on the validation set.

**Error:**
"Unable to Load Checkpoint."
if I print the exception at that `except` statement I get the following error `bad marshal data`

**Cause:**
I think this problem is caused by the different python / tensorflow versions used to generate the model and in my runtime.
My versions are:
- python 3.10.4 / python 3.8
- tensorflow 2.9.2
- keras 2.9.0

**Solution:**
I sovled the problem by running tensroflow 2.9.0 with python 3.7 in a docker container and saving the model as a "tensorflow saved model" Format instead of keras H5 Format. Now it works with the newer version of python.

**Suggestion:**
Add a tensorflow saved model format checkpoint to support more python/tensorflow versions.

PS: there was another problem while loading the model which is a missing `'k': K` in the `custom_objects={...}`

**Comment by myselfRJ** [comment]
In predict.py add this
'tensorflow':tf, 'K':K
instead of 'tf':tf

**Comment by Bhavyan761** [comment]
Can you share your TensorFlow saved model here?

**Comment by kartikgill** [comment]
Thanks @Mekacher-Anis and @myselfRJ for trying our Easter2 and your valuable suggestions.

**Comment by cs-mshah** [comment]
I did all this but now I am getting the following error from keras which is surprising:
```python
AttributeError                            Traceback (most recent call last)
<ipython-input-3-75a2b235dbeb> in <module>
----> 1 test_on_iam(show=False, partition="validation", checkpoint=checkpoint_path, uncased=True)

~/projects/Easter2/src/predict.py in test_on_iam(show, partition, uncased, checkpoint)
     90             img = imgs[i]
     91             truth = truths[i].strip(" ").replace("  "," ")
---> 92             output = model.predict(img)
     93             prediction = decoder(output, charlist)
     94             output = (prediction[0].strip(" ").replace("  ", " "))

~/anaconda3/lib/python3.7/site-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

~/anaconda3/lib/python3.7/site-packages/keras/engine/data_adapter.py in _get_tensor_types()
   1660     return (tf.Tensor, np.ndarray)
   1661   else:
-> 1662     return (tf.Tensor, np.ndarray, pd.Series, pd.DataFrame)
   1663 
   1664 

AttributeError: module 'pandas' has no attribute 'Series'
```

**Comment by SaimZahir** [comment]
I am also unable to load model either in h5 format or keras default format. following is the error encountered
<img width="677" alt="Screenshot 2022-11-17 180526" src="https://user-images.githubusercontent.com/106699327/202454323-ae849b03-aa92-475c-af4c-b14fdf2588f5.png">

**Comment by Mekacher-Anis** [comment]
@SaimZahir I think that's caused by the different python/tensorflow/keras versions.
I have uploaded my saved_model here https://sf.anismk.de/static/saved_model.zip give it a try, but make sure to setup `custom_objects` correctly

**Comment by SaimZahir** [comment]
i have tried with tensorflow 2.9 but same issue is going on

**Comment by Mekacher-Anis** [comment]
I load my model using
```py
EASTER = tensorflow.keras.models.load_model(
            checkpoint_path,
            custom_objects={'<lambda>': lambda x, y: y,
            'tf':tf, 'K': K
            },
        )
```

**Comment by kartikgill** [comment]
Thanks everyone for trying out EASTER...I hope everything works fine for everyone. 

Closing this issue for now...please feel free to reopen if needed. Thanks.
