### ISSUE TITLE
Test on individual images

### ISSUE THREAD

**Issue by PilliSiddharth** [kartikgill/Easter2#6]
Hi, can you please provide a notebook or code for testing on individual images?

**Comment by Michael95-m** [comment]
Hi @PilliSiddharth, I wrote a predict script for you. I hope it can help you. Please read carefully the comments I wrote for you.

```python
## you need to run this script inside src folder
## predict_test.py; which is made for single line images
## I assume you installed the dependencies and downloaded the IAM dataset as described in readme file 

from data_loader import data_loader
import config
from predict import load_easter_model
import cv2
import numpy as np
import itertools

def preprocess(img):
            
    # preprocessing is needed 
    img = img/255
    img = img.swapaxes(-2,-1)[...,::-1]
    target = np.ones((config.INPUT_WIDTH, config.INPUT_HEIGHT))
    new_x = config.INPUT_WIDTH/img.shape[0]
    new_y = config.INPUT_HEIGHT/img.shape[1]
    min_xy = min(new_x, new_y)
    new_x = int(img.shape[0]*min_xy)
    new_y = int(img.shape[1]*min_xy)
    img2 = cv2.resize(img, (new_y,new_x))
    target[:new_x,:new_y] = img2
    return 1 - (target)

def decoder(output,letters):
    ret = []
    for j in range(output.shape[0]):
        out_best = list(np.argmax(output[j,:], 1))
        out_best = [k for k, g in itertools.groupby(out_best)]
        outstr = ''
        for c in out_best:
            if c < len(letters):
                outstr += letters[c]
        ret.append(outstr)
    return ret

## rewritten class file for efficient prediction

class infer_img:
    
    def __init__(self, charlist):
        
        self.model = load_easter_model(config.BEST_MODEL_PATH)
        self.charlist = charlist
        
    def predict(self, img_path):
        
        img1 = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        img = preprocess(img1)
        img = np.expand_dims(img,  0)
        output = self.model.predict(img)
        prediction = decoder(output, self.charlist)
        
        return prediction[0]

if __name__ == "__main__":

    ## actually data_loader with data path is not needed; but in that case, charlist is needed to be extracted 
    ## so training data is loaded

    training_data = data_loader(config.DATA_PATH, config.BATCH_SIZE)
    charlist = training_data.charList

    ## instead of loading the data path, you can write the charlist file in your local storage for the next time.
    ##  And load charlist from the text file instead of using data_loader
    infer_obj = infer_img(charlist)

    print(infer_obj.predict("../data/lines/c04/c04-000/c04-000-00.png")) ## change the image path with the file path you want

## **Note**: this prediction is only good with line level images because this model has trained on IAM dataset which contains only line level images. If you want to predict the real world images which contain multiple lines, firstly you need to extract the line level images from it  by means of image processing or neural nets and predict each image through the given easter model.
```

**Comment by musharaf-hossain-cs** [comment]
Traceback (most recent call last):
  File "h:\Desktop_Files\CSE472\Project\ExistingCode\Easter2\test\test_image.py", line 77, in <module>
    print(infer_obj.predict(file)) ## change the image path with the file path you want
  File "h:\Desktop_Files\CSE472\Project\ExistingCode\Easter2\test\test_image.py", line 57, in predict
    output = self.model.predict(img)
  File "C:\Users\musha\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\musha\AppData\Local\Temp\__autograph_generated_file9laosjz9.py", line 15, in tf__predict_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
ValueError: in user code:

    File "C:\Users\musha\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\training.py", line 2137, in predict_function  *       
        return step_function(self, iterator)
    File "C:\Users\musha\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\training.py", line 2123, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\musha\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\training.py", line 2111, in run_step  **
        outputs = model.predict_step(data)
    File "C:\Users\musha\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\training.py", line 2079, in predict_step
        return self(x, training=False)
    File "C:\Users\musha\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\musha\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\input_spec.py", line 216, in assert_input_compatibility
        raise ValueError(

    ValueError: Layer "model_1" expects 4 input(s), but it received 1 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(None, 2000, 80) dtype=float32>]

**Comment by Michael95-m** [comment]
The original code works  only on python 3.7 and tensorflow 1.4. I saw you used python 3.9. And Can u check  the prediction with my [repo](https://github.com/Michael95-m/Easter2).

**Comment by kartikgill** [comment]
Thanks @Michael95-m for providing working code for the issue.

@musharaf-hossain-cs I hope your issue is resolved now. so closing this issue....feel free to reopen if need be. Thanks.
