### ISSUE TITLE
text extraction using ocr

### ISSUE THREAD

**Issue by swetharethinavel** [kartikgill/Easter2#7]
If i give a cropped image with a handwritten text in a line ,it is difficult to recognize and i'm getting wrong predicted output.
instead if i give the same without the  text touching the line ,then i could extract the text without any mistake.
input:
<img width="62" alt="c04-156-06" src="https://user-images.githubusercontent.com/115137983/194232675-87a4ab44-d88f-4326-9d32-45176a9e84e1.png">
output:

<img width="312" alt="output 06" src="https://user-images.githubusercontent.com/115137983/194232827-6bb6cf53-e8d1-42b5-b8dd-2390e207b65b.png">

so,let me know how could it be resolved!

**Comment by PilliSiddharth** [comment]
Can you provide your code?

**Comment by swetharethinavel** [comment]
i haven't changed anything ,i just gitclone the model easter 2.0 and did a little alteration in testing.txt ,but i gave the different test image in the same format .actually the model is working without lines .
but the thing is ,help me out to extract the correct txt even if it is given in line .

**Comment by PilliSiddharth** [comment]
I need to understand the changes though

**Comment by swetharethinavel** [comment]
i have only altered the testing images similar to the iam dataset

**Comment by kartikgill** [comment]
Thanks @swetharethinavel for trying out Easter2. 

I understand your concern. This pre-trained model is only trained to IAM dataset, so it has seen only clean images (no underlines).  

In order to make it work for underlined images - you may have to train it further with some underlined training samples. In this way, model should start working on underlined text as well.

**Comment by swetharethinavel** [comment]
@kartikgill can we use this easter model to extract the numbers from an document?

**Comment by itsbvk** [comment]
@swetharethinavel kindly understand that deep learning models are generally very sensitive to the data distribution. I believe that the IAM dataset is not explicitly trained to recognize numbers. If you however want to use this model for extraction you will have to finetune your data.

You can however use google's cloud vision API for off-the shelf usage - which seem to do pretty well.

**Comment by kartikgill** [comment]
Hey @swetharethinavel ,

I understand your concern. But, as @khadiravana-belagavi rightly mentioned that deep learning model only learns what it sees in training data..so in case you want it to work on numbers or maybe another language...kindly provide some relevant data samples and finetune it. I hope it clears your doubt. Thanks.

Just to give you confidence - During my project, i have tried Easter for different things like - numbers, symbols etc. And, it did great as long as you have proper training samples. 

I hope this clears your doubt...closing the issue for now. Please feel free to reopen if need be. Thanks.
