### ISSUE TITLE
How to select the super parameters for data argument, especially T_ Max

### ISSUE THREAD

**Issue by BigTree765** [kartikgill/Easter2#8]
Your work is of great application value. Vertical tiles can improve the performance. But how to select the super parameters for data argument, especially T_ Max, i think this should be related to the height of the text line. can you give me some suggestions.

**Comment by kartikgill** [comment]
Hey @yusirhhh ,

Thanks for checking it out!

T_MAX is purely experimental...We got good results when it is roughly equal to the width of individual character of handwriting (or from another perspective - roughly equal to the height or image). 


But, as you have rightly mentioned that it is a hyperparameter...it can be tuned for different datasets. Thanks.

Closing it for now..feel free to reopen if needed.
